export interface Candidate {
  id: string;
  firstName: string;
  lastNameInitial: string;
  fullName: string;
  city: string;
  country: string;
  photo: string;
  overallScore: number;
  vettingScore: number;
  mandatoryCoursesScore: number;
  lawfirmCoursesScore: number;
  discType: 'D' | 'I' | 'S' | 'C';
  discDescription: string;
  role: 'Intake Specialist' | 'Paralegal / Case Manager' | 'Admin' | 'Hybrid';
  coursesCompleted: string[];
  taskCertifications: string[];
  status: 'passed' | 'failed' | 'in-training' | 'ready';
}

const DISC_DESCRIPTIONS = {
  D: 'Dominance - Direct, results-oriented, firm, strong-willed, and forceful. Thrives in competitive environments and excels at making quick decisions.',
  I: 'Influence - Outgoing, enthusiastic, optimistic, high-spirited, and lively. Excels at building relationships and motivating others through positivity.',
  S: 'Steadiness - Even-tempered, accommodating, patient, humble, and tactful. Values cooperation and stability, excellent team player.',
  C: 'Conscientiousness - Analytical, reserved, precise, private, and systematic. Focuses on quality and accuracy, excels at detailed work.'
};

export const CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    firstName: 'María',
    lastNameInitial: 'G',
    fullName: 'María García',
    city: 'Bogotá',
    country: 'Colombia',
    photo: 'https://mgx-backend-cdn.metadl.com/generate/images/891635/2026-01-13/172754c1-70dc-47e6-b92b-2cb4c8f05955.png',
    overallScore: 96,
    vettingScore: 98,
    mandatoryCoursesScore: 95,
    lawfirmCoursesScore: 95,
    discType: 'I',
    discDescription: DISC_DESCRIPTIONS.I,
    role: 'Intake Specialist',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-2',
    firstName: 'Luis',
    lastNameInitial: 'P',
    fullName: 'Luis Pérez',
    city: 'Guadalajara',
    country: 'Mexico',
    photo: 'https://mgx-backend-cdn.metadl.com/generate/images/891635/2026-01-13/fc76ff96-24f0-4a9a-9d16-01bc52bcb8b0.png',
    overallScore: 94,
    vettingScore: 96,
    mandatoryCoursesScore: 93,
    lawfirmCoursesScore: 93,
    discType: 'D',
    discDescription: DISC_DESCRIPTIONS.D,
    role: 'Paralegal / Case Manager',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-3',
    firstName: 'Ana',
    lastNameInitial: 'R',
    fullName: 'Ana Rodríguez',
    city: 'Lima',
    country: 'Peru',
    photo: 'https://mgx-backend-cdn.metadl.com/generate/images/891635/2026-01-13/aa25d62d-01a0-47e5-82e0-38513de2bf93.png',
    overallScore: 93,
    vettingScore: 95,
    mandatoryCoursesScore: 92,
    lawfirmCoursesScore: 92,
    discType: 'C',
    discDescription: DISC_DESCRIPTIONS.C,
    role: 'Admin',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-4',
    firstName: 'Carlos',
    lastNameInitial: 'M',
    fullName: 'Carlos Martínez',
    city: 'Buenos Aires',
    country: 'Argentina',
    photo: 'https://mgx-backend-cdn.metadl.com/generate/images/891635/2026-01-13/91a0d0a8-3340-441c-8e07-446b4f60d385.png',
    overallScore: 92,
    vettingScore: 93,
    mandatoryCoursesScore: 91,
    lawfirmCoursesScore: 92,
    discType: 'S',
    discDescription: DISC_DESCRIPTIONS.S,
    role: 'Hybrid',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-5',
    firstName: 'Sofia',
    lastNameInitial: 'L',
    fullName: 'Sofia López',
    city: 'Santiago',
    country: 'Chile',
    photo: 'https://mgx-backend-cdn.metadl.com/generate/images/891635/2026-01-13/fb092b61-69d4-4f80-877d-7f7b0577c050.png',
    overallScore: 91,
    vettingScore: 93,
    mandatoryCoursesScore: 90,
    lawfirmCoursesScore: 90,
    discType: 'I',
    discDescription: DISC_DESCRIPTIONS.I,
    role: 'Intake Specialist',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-6',
    firstName: 'Diego',
    lastNameInitial: 'S',
    fullName: 'Diego Sánchez',
    city: 'Medellín',
    country: 'Colombia',
    photo: 'https://mgx-backend-cdn.metadl.com/generate/images/891635/2026-01-13/9c9cc543-5074-4c39-af0e-7cd10b9e81a8.png',
    overallScore: 90,
    vettingScore: 92,
    mandatoryCoursesScore: 89,
    lawfirmCoursesScore: 89,
    discType: 'D',
    discDescription: DISC_DESCRIPTIONS.D,
    role: 'Paralegal / Case Manager',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-7',
    firstName: 'Isabella',
    lastNameInitial: 'T',
    fullName: 'Isabella Torres',
    city: 'Mexico City',
    country: 'Mexico',
    photo: '/images/IsabellaTorres.jpg',
    overallScore: 89,
    vettingScore: 91,
    mandatoryCoursesScore: 88,
    lawfirmCoursesScore: 88,
    discType: 'C',
    discDescription: DISC_DESCRIPTIONS.C,
    role: 'Admin',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-8',
    firstName: 'Miguel',
    lastNameInitial: 'V',
    fullName: 'Miguel Vargas',
    city: 'Quito',
    country: 'Ecuador',
    photo: '/images/MiguelVargas.jpg',
    overallScore: 88,
    vettingScore: 90,
    mandatoryCoursesScore: 87,
    lawfirmCoursesScore: 87,
    discType: 'S',
    discDescription: DISC_DESCRIPTIONS.S,
    role: 'Hybrid',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-9',
    firstName: 'Valentina',
    lastNameInitial: 'C',
    fullName: 'Valentina Castro',
    city: 'San José',
    country: 'Costa Rica',
    photo: '/images/ValentinaCastro.jpg',
    overallScore: 87,
    vettingScore: 89,
    mandatoryCoursesScore: 86,
    lawfirmCoursesScore: 86,
    discType: 'I',
    discDescription: DISC_DESCRIPTIONS.I,
    role: 'Intake Specialist',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-10',
    firstName: 'Andrés',
    lastNameInitial: 'H',
    fullName: 'Andrés Hernández',
    city: 'Guatemala City',
    country: 'Guatemala',
    photo: '/images/AndrsHernndez.jpg',
    overallScore: 86,
    vettingScore: 88,
    mandatoryCoursesScore: 85,
    lawfirmCoursesScore: 85,
    discType: 'D',
    discDescription: DISC_DESCRIPTIONS.D,
    role: 'Paralegal / Case Manager',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-11',
    firstName: 'Camila',
    lastNameInitial: 'F',
    fullName: 'Camila Flores',
    city: 'La Paz',
    country: 'Bolivia',
    photo: '/images/CamilaFlores.jpg',
    overallScore: 85,
    vettingScore: 87,
    mandatoryCoursesScore: 84,
    lawfirmCoursesScore: 84,
    discType: 'C',
    discDescription: DISC_DESCRIPTIONS.C,
    role: 'Admin',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-12',
    firstName: 'Ricardo',
    lastNameInitial: 'D',
    fullName: 'Ricardo Díaz',
    city: 'Managua',
    country: 'Nicaragua',
    photo: '/images/RicardoDaz.jpg',
    overallScore: 84,
    vettingScore: 86,
    mandatoryCoursesScore: 83,
    lawfirmCoursesScore: 83,
    discType: 'S',
    discDescription: DISC_DESCRIPTIONS.S,
    role: 'Hybrid',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-13',
    firstName: 'Lucía',
    lastNameInitial: 'A',
    fullName: 'Lucía Alvarez',
    city: 'Tegucigalpa',
    country: 'Honduras',
    photo: '/images/LucaAlvarez.jpg',
    overallScore: 83,
    vettingScore: 85,
    mandatoryCoursesScore: 82,
    lawfirmCoursesScore: 82,
    discType: 'I',
    discDescription: DISC_DESCRIPTIONS.I,
    role: 'Intake Specialist',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-14',
    firstName: 'Fernando',
    lastNameInitial: 'O',
    fullName: 'Fernando Ortiz',
    city: 'San Salvador',
    country: 'El Salvador',
    photo: '/images/FernandoOrtiz.jpg',
    overallScore: 82,
    vettingScore: 84,
    mandatoryCoursesScore: 81,
    lawfirmCoursesScore: 81,
    discType: 'D',
    discDescription: DISC_DESCRIPTIONS.D,
    role: 'Paralegal / Case Manager',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-15',
    firstName: 'Daniela',
    lastNameInitial: 'N',
    fullName: 'Daniela Navarro',
    city: 'Bogotá',
    country: 'Colombia',
    photo: '/images/DanielaNavarro.jpg',
    overallScore: 81,
    vettingScore: 83,
    mandatoryCoursesScore: 80,
    lawfirmCoursesScore: 80,
    discType: 'C',
    discDescription: DISC_DESCRIPTIONS.C,
    role: 'Admin',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-16',
    firstName: 'Javier',
    lastNameInitial: 'R',
    fullName: 'Javier Ramírez',
    city: 'Lima',
    country: 'Peru',
    photo: '/images/JavierRamrez.jpg',
    overallScore: 80,
    vettingScore: 82,
    mandatoryCoursesScore: 79,
    lawfirmCoursesScore: 79,
    discType: 'S',
    discDescription: DISC_DESCRIPTIONS.S,
    role: 'Hybrid',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-17',
    firstName: 'Gabriela',
    lastNameInitial: 'M',
    fullName: 'Gabriela Morales',
    city: 'Santiago',
    country: 'Chile',
    photo: '/images/GabrielaMorales.jpg',
    overallScore: 79,
    vettingScore: 81,
    mandatoryCoursesScore: 78,
    lawfirmCoursesScore: 78,
    discType: 'I',
    discDescription: DISC_DESCRIPTIONS.I,
    role: 'Intake Specialist',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-18',
    firstName: 'Pablo',
    lastNameInitial: 'J',
    fullName: 'Pablo Jiménez',
    city: 'Buenos Aires',
    country: 'Argentina',
    photo: '/images/PabloJimnez.jpg',
    overallScore: 78,
    vettingScore: 80,
    mandatoryCoursesScore: 77,
    lawfirmCoursesScore: 77,
    discType: 'D',
    discDescription: DISC_DESCRIPTIONS.D,
    role: 'Paralegal / Case Manager',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-19',
    firstName: 'Natalia',
    lastNameInitial: 'B',
    fullName: 'Natalia Benítez',
    city: 'Medellín',
    country: 'Colombia',
    photo: '/images/Colombia.jpg',
    overallScore: 77,
    vettingScore: 79,
    mandatoryCoursesScore: 76,
    lawfirmCoursesScore: 76,
    discType: 'C',
    discDescription: DISC_DESCRIPTIONS.C,
    role: 'Admin',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
  {
    id: 'cand-20',
    firstName: 'Sebastián',
    lastNameInitial: 'K',
    fullName: 'Sebastián Keller',
    city: 'Mexico City',
    country: 'Mexico',
    photo: '/images/SebastinKeller.jpg',
    overallScore: 76,
    vettingScore: 78,
    mandatoryCoursesScore: 75,
    lawfirmCoursesScore: 75,
    discType: 'S',
    discDescription: DISC_DESCRIPTIONS.S,
    role: 'Hybrid',
    coursesCompleted: [],
    taskCertifications: [],
    status: 'ready',
  },
];
